### PR TITLE
added chessboard view

### PR DESCRIPTION
**Pull request by nrabbi**
Built a view for the chess board.

### CODE REVIEW

**Comment by nrabbi** [comment]
Don't forget to remove the 'board' branch after the pull request has been reviewed and merged to master.

**Comment by ezschemi** [comment]
Why not do a simple HTML-table instead of Javascript? What is the advantage of using Javascript paint actions?

**Comment by nrabbi** [comment]
@ezschemi done

**Comment by fleawig** [comment]
I'm going to approve and merge just so there's a board on master branch, but surely there is a DRYer way to write the view! It would be nice to see squares labelled for reading coordinates, also.

**Pull request merged**
