### PR TITLE
Application Front-End Interface

### PR DESCRIPTION
**Pull request by nrabbi**
Working on interface

### CODE REVIEW

**Comment by rongg** [comment]
The changes I've pushed are pretty self-explanatory in the commits-- just trying to follow the wireframe with the exception of the list of moves(new), which will be to the side of the board on large screens. For medium and below(< 1024 px) the moves list will appear at the bottom of the board.

@nrabbi There's an inconsistency between the header font- robotic looking- and the rest of the fonts. Wouldn't it be best to keep them the same? The background image is also very random(fruit!), maybe something more subtle?

**Comment by nrabbi** [comment]
@rongg I had different fonts for the application and the navbar on purpose. I will change the font and the background as suggested.

**Comment by rongg** [comment]
@nrabbi After reading a bit on fonts and design, it doesn't seem like the end of the world to have different fonts. I would suggest only that they complement each other well. This may help:

[Font Pair](http://fontpair.co)

**Comment by nrabbi** [comment]
The game#show action and view were unnecessary as we can directly go the game board from the available games page. So removed that extra stuff that is not needed.

**Comment by nrabbi** [comment]
All Front end tasks from my end are complete. Once @rongg finishes all the tasks then this pull request will be ready for merge.

**Comment by rongg** [comment]
Looking good. One issue though- the footer on the home page, available games, and new game is not sticking to the bottom. @nrabbi Do you know why this is? I took a quick stab at it but couldn't figure out why the board view is has a good footer but the others don't. 

Waiting on this and the final 3 check items to merge.

**Comment by nrabbi** [comment]
@rongg can you send me a screenshot of this not sticking issue. In my local machine, it looks fine.

**Comment by rongg** [comment]
@nrabbi images in slack

**Comment by nrabbi** [comment]
@rongg fixed footer, ready for review.

**Comment by rongg** [comment]
@nrabbi Do the changes address the issue raised by Enrico in slack(twitter misplaced)?

**Comment by nrabbi** [comment]
@rongg I just saw his message, but yeah that particular issue seems to be fixed in the updated footer.

**Review by rongg — DISMISSED** [review]

**Comment by rongg** [comment]
@nrabbi @ezschemi @fleawig Going to merge this by 5pm tomorrow(PST) unless there are issues.

**Review by ezschemi — CHANGES_REQUESTED** [review]
The chessboard has fixed width, which is a problem in High Resolution screens, such as my 4k 27" monitor at work. The board is very small, the pieces even smaller.

Another big issue:
when one has scrolled down and the header is not visible anymore, it is easy for all notifications to disappear to. There is no other hint that there was an error.

Smaller issues: 
 * Team-page is empty
 * Privacy Policy is empty
 * LinkedIn link is wrong
 * twitter link is wrong

**Comment by nrabbi** [comment]
@ezschemi I am going to clarify the smaller issues you brought up as that was my part of the front end work. All these are placeholder items, and they don't point anywhere (on purpose), it's there so we can add these stuff later on. And this is not going to be addressed as part of this task.

**Comment by rongg** [comment]
@ezschemi @nrabbi It looks like we have a responsive app minus the chessboard. I was going to address this later but it's probably best to finish now so we can move on to the rest of the app.

For the notifications, I've replaced the inline ruby with a javascript [toast.](http://codeseven.github.io/toastr/demo.html) Let me know if this is good.

**Comment by rongg** [comment]
Made use of Sass variables and media queries to make the board responsive to different screen sizes.

**Pull request merged**
