### PR TITLE
Turn logic

### PR DESCRIPTION
**Pull request by fleawig**
This branch includes:
Keeps track of whose turn it is from the move count, as "Black" or "White"
Updates after move creation.
Board view displays which color has turn.
Wrong player prohibited from creating a move, with an alert.
Tests on these functions.

### CODE REVIEW

**Review by ezschemi — COMMENTED** [review]
@fleawig I am not sure if this is expected and still work-in-progress or not: 
1) Create a brand new game
2) Move a white pawn
3) Try to move a black pawn.

Step 3 errors out with:
```
Hey, it's not your turn!
```

**Comment by fleawig** [comment]
Perfect! By "errors out" you mean it puts an error notice to the screen, and does not update the board, right?
To make move #2, you must be signed in as a different user, and you must have joined this game. Otherwise it's not your turn. In this case it sounds like you chose White for Player 1, so you would need to sign in a Player 2 to join as Black.

In short: 
Player 1 creates game and chooses their color.
Player 2 can join game and is assigned opposite color.
White's turn is first.
Black's turn is second.
Etc.

**Comment by fleawig** [comment]
Ps -- a list of games you can join is at /games/available

**Comment by fleawig** [comment]
If you want, we could add each player's email and color to the board view, to make it easier to keep track, something like:
You are <current_player email>, White
Your opponent is <other_email>, Black
It's currently White's turn

**Comment by rongg** [comment]
@fleawig Tried multiple scenarios with 2 users and couldn't get it to work :( 

How is player 2 assigned the opposite color? I'm looking at the db for the games and player_2_id is always nil. Is 'View Game Board' supposed to do something?

**Comment by rongg** [comment]
After some confusion I was able to get it working. I was conflating the list of "all" games with "available" games, then read your comment and voila! 

As for indicating whose turn it is, I always like when then it's addressed directly, such as "It's your turn". It would be nice if the board was inverted so the current user is always facing up, but since that feature is not present the design in the wireframe should do as that indicates who is black and white.

**Review by rongg — DISMISSED** [review]

**Comment by fleawig** [comment]
Cool, thanks Ron. I added a few methods to game controller, and more turn/opponent/color info is now in the board view. But I'd also like to make 2 more changes: 
1. prevent White moves before player 2 joins (by checking status) 
2. replace some references to current_player, for handling when a third player views the game board.
After I make these changes today I'll notify for review.

**Review by nrabbi — APPROVED** [review]

**Review by nrabbi — COMMENTED** [review]
Everything seems good so far keep it up 👍

**Comment by fleawig** [comment]
@rongg @ezschemi @nrabbi 
Thanks Nazmul! So, I've pushed up the following methods and changes to board:
Prohibit players from making moves when: 
  They are not signed in
  They haven't joined the game
  There is no Player 2
  It isn't their color's turn
  They try to move the wrong color piece
Also, made methods and links for the following:
  If current_player in game, board personalized: "You are playing as ____" "Your opponent is ____" etc
  If no current_player or not in game, not personalized: "xxx@xxx.com is playing as ___"
Still fixing one last test which has trouble posting second move, but I wanted to make sure people working on the interface had access to these methods for personalizing view output.

**Comment by rongg** [comment]
Just a heads up- there will be conflicts with the interface branch with perhaps some duplicated work pertaining to black vs white and who is who. This shouldn't be a problem as all we would have to do is resolve which backend code will support the view.

**Pull request merged**
