### PR TITLE
Basic crud for game

### PR DESCRIPTION
**Pull request by fleawig**
For now this lets you make a new game, view a list of games, view a game show page, and view the board for that game off the show page. We can do plenty more to this later -- I just wanted it set up so we can make @game.moves CRUD

### CODE REVIEW

**Comment by fleawig** [comment]
Just realized I missed pulling in the changes to schema which removed User and ChessPiece tables. Will update this so it's not re-adding those.

**Comment by fleawig** [comment]
Ready to go now, please review. I'm moving on to actually building basic CRUD for game.moves

**Comment by rongg** [comment]
This was breaking my migrations because I didn't have a Users or ChessPiece table, so I added a check for dropping only if the table exists.

**Review by rongg — APPROVED** [review]

**Review by nrabbi — APPROVED** [review]

**Comment by fleawig** [comment]
Thanks for that change, Ron.

**Pull request merged**
