### PR TITLE
Live updates with actioncable

### PR DESCRIPTION
**Pull request by rongg**
Hey everyone. This pull makes our app realtime, alerting the user and updating the view without refresh:

- Joining game
- Movement: success, invalid, not allowed. Updates board and adds to list.
- Turn indication

There are now 2 ways to generate the current state of the board. The first is navigating to game#board, running apply moves and letting the inline ruby generate the template, and the second is turn by turn with ActionCable.

### CODE REVIEW

**Review by fleawig — APPROVED** [review]
Looks good!

**Review by nrabbi — APPROVED** [review]

**Comment by ezschemi** [comment]
@rongg Where did the indicator go for whose turn it is? This is the game view now:
image

**Comment by rongg** [comment]
Turn indication is shown by the player's email is being green(other is red)
and having the word "Turn" prepended to it.

On Mon, Mar 6, 2017 at 11:18 PM, Enrico Zschemisch <notifications@github.com

**Comment by nrabbi** [comment]
I also had this issue while testing. It took me a good 30 secs to understand this color change. I think instead of just changing the color if there is also a text background for the active player, that would make it easier to distinguish.

**Pull request merged**
