### PR TITLE
Crud for moves 2

### PR DESCRIPTION
**Pull request by fleawig**
CRUD for Moves now allows us to enter real moves. 
Button for new move on game/:id/board view goes to form.
Form takes integer values for square (see Position for the index).
After create, redirect to board view which updates pieces and lists all moves.
All of this can be styled or rearranged later, but for now we have a working interface.
Next: Integrate move rules/checks.

### CODE REVIEW

**Comment by fleawig** [comment]
Rspec fails because of a hard-coded game_id value in a controller test. Will edit this.

**Comment by fleawig** [comment]
Go to /games/2/board to see an example game board with a few moves. You can try adding moves yourself and see the board get updated. Or you can start @ root and view games, add moves, add new game and moves, etc.

**Review by nrabbi — APPROVED** [review]

**Comment by nrabbi** [comment]
@fleawig everything seems to work correctly. The only thing I can't test is the board when I visit localhost:3030/games/2/board it throws an error.  ActiveRecord::RecordNotFound in GamesController#board
Couldn't find Game with 'id'=2

Note: I also ran migrations so that is not the issue.

**Review by nrabbi — CHANGES_REQUESTED** [review]
@fleawig everything seems to work correctly. The only thing I can't test is the board view when I visit localhost:3030/games/2/board it throws an error.

> 
> ActiveRecord::RecordNotFound in GamesController#board
> Couldn't find Game with 'id'=2

**Note:** I also ran migrations, so that is not the issue.

**Review by rongg — APPROVED** [review]
Working on my end!

**Comment by fleawig** [comment]
@nrabbi Thanks for the style corrections. Not sure why that game is in the db for Ron but not you. Could you try deleting your local copy of the branch and then re-checkout it locally?

**Comment by ezschemi** [comment]
Database content is not stored in git. Unless you added a seed
file (seed.rb) there is basically no way for us to have the same
game(s) as you.


Enrico







On Fri, Feb 3, 2017, at 08:42, fleawig wrote:

> @nrabbi[1] Thanks for the style corrections. Not sure why that game is
> in the db for Ron but not you. Could you try deleting your local copy
> of the branch and then re-checkout it locally?
> — You are receiving this because your review was requested. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/nrabbi
  2. https://github.com/thesnowcoders-fh/sprky-chess/pull/19#issuecomment-277184114

**Comment by rongg** [comment]
Should add I had to delete all existing games from local db and restart
server to get it to work

**Comment by fleawig** [comment]
Good point about db content. That should not affect this merge, anyway. Go ahead and clear your db, go to home page, make a new game, and add some moves, or test it out however else you like. Sounds like my link to game with id: 2 was too specific.

**Review by nrabbi — APPROVED** [review]
Approved. Everything is working great. Ready for merge!

**Review by ezschemi — APPROVED** [review]

**Pull request merged**
