### PR TITLE
capture logic 

### PR DESCRIPTION
**Pull request by nrabbi**
working on capture logic method as well as updated pawn methods (In Progress)

### CODE REVIEW

**Comment by rongg** [comment]
The tests have failed because the code is not implemented yet.

**Comment by rongg** [comment]
@ezschemi I added an expected return type for the move_to method. False for bad moves and true for success. That way the controller knows about the status of an attempted move for alerting the user and such.

**Comment by ezschemi** [comment]
The pawn code on this branch violates the ChessPiece-interface. Pawn code:
```
 def is_valid?(pieces, destination)
    return false if can_capture?(pieces, destination) == false && (inside_board_boundaries?(destination.x, destination.y) == false || color == :white && destination.y < position.y || color == :black && destination.y > position.y || destination.x != position.x || pawn_unused? == true && (position.y - destination.y).abs > 2)

    true
  end
```

whereas the interface is defined as:
```
def is_valid?(_destination)
```

which now makes all movement code not work anymore. 

This blocks my work.

**Comment by nrabbi** [comment]
@ezschemi will rewrite the code. It wont take long.

**Comment by ezschemi** [comment]
@nrabbi Ok, I will wait then.

**Comment by ezschemi** [comment]
@rongg A binary return value won't work for move_to: I need to report if there was an error and if so, what the error is. 
Error as in "this move is invalid", "this piece is obstructed", etc. and not an application exception.

**Comment by nrabbi** [comment]
@ezschemi It's fixed now. ~~One test is not going to pass now due to the code rewrite (test is put to pending). I will add that implementation soon.~~

**Comment by rongg** [comment]
@ezschemi How about a return type of String? We can make the return values constants in PieceMover.

**Comment by fleawig** [comment]
@ezschemi Did you rename the class from PieceMover to MoveResolution? I would expect this to  cause problems for Rails finding the class. It would expect a filename like move_resolution.rb. The function may have changed but this may need to be resolved.

**Comment by ezschemi** [comment]
@fleawig Not renamed. I added a class. This can be in a separate file or the definition can be close to the actual usage. Makes it easier to read the piece of code.

**Comment by fleawig** [comment]
I see -- you just added another class in the same document. It seems like that should be moved to another service.

**Comment by fleawig** [comment]
I missed that initially. I can see how that would make it easier to read, though I could also definitely see it being its own service.

**Comment by ezschemi** [comment]
@fleawig @rongg @nrabbi can we merge this, to make progress with the other tasks?

**Comment by rongg** [comment]
@ezschemi, @nrabbi, @fleawig  Hold on. Been playing around with it and the movement's not working. Some observations:

- Pawn movement not working. I'm able to move diagonally.
- Apply moves is crashing on attempted capture
- Some of the obstruction is not being properly reported. For example when moving the King or Queen I've gotten a move resolution of 'obstructed' when there really was nothing in the way.
- The list of moves is correct, but are not being applied properly. So the view doesn't know where the pieces are, which paralyzes further movement.

I can't take a stab at making all of this work until Saturday but if anyone else can figure what's wrong in the meantime you can play with it now with the changes from ui-move now included in this branch.

**Comment by nrabbi** [comment]
@rongg only checking the valid method will allow diagonal movement by default as that was done by design. If you want detailed explanation why such decisions were made I can give you brief explanation later. 

~~**Working on a fix!**~~

~~The fix for this is to define the following:~~

~~> if pawn_movement_valid == true and pawn_is_obstructed == false then execute the move ``~~

**Comment by ezschemi** [comment]
@nrabbi define this where? and where shall this be used?

**Comment by nrabbi** [comment]
@ezschemi The other methods in the pawn class was supposed to block the invalid diagonal movements that the valid method allows the pawns to have.  That's basically what i was saying. ~~If that is not the case I will fix this bug before our meeting.~~

**Comment by nrabbi** [comment]
@rongg I~~t's fixed just had to change one number from 1 to 0 lol. One side effect is that every diagonal~~ ~~movement will now return false regardless of being valid or not.~~

~~**Note:** Pawns can only move diagonally only if a capture operation can be performed. Running~~ ~~can_capture? alone should return true if a piece is able to be captured.~~

**Update:** Seems like the way i was doing it before was correct but need to add one check to fix it. Expect the bug fix to come before our meeting on Sunday. One check inside the obstruction method should fix this.~~

**Comment by nrabbi** [comment]
Tested my new pawn code by creating a new board. Now all pawn movements seem to work on the board. 😏 😤 💯 🥇

**Comment by ezschemi** [comment]
@nrabbi @rongg @fleawig Can you review again, so we can merge this on Sunday?

**Comment by nrabbi** [comment]
The code looks good so far. Ready for the merge! 👍

**Review by rongg — APPROVED** [review]
Nice code everybody 👍

**Review by fleawig — CHANGES_REQUESTED** [review]
Lots of fantastic work here. Just one issue: king-checking was moved in here but then left unresolved. I asked Enrico about it in our Slack before he requested this review -- please check there for more details. We could go ahead and merge this in, and then finish that part on a new branch, or we could split that part off before this merge.

**Comment by ezschemi** [comment]
After better understanding the changes requested by @fleawig I have remove the check-checking code from this branch. Will merge this PR now.

**Pull request merged**
