### PR TITLE
Failing tests

### PR DESCRIPTION
**Pull request by ezschemi**
I have adapted some of the tests to the new code structure and integrated the code from Trello. 

There are still failing tests for the chess pieces because of missing implementations. We need to quickly decided how to move forward:

1) deactivate the tests until the implementations are ready
2) add the implementations to this branch, then use this branch to fix all tests. 

I am strongly leaning towards 2.

### CODE REVIEW

**Comment by ezschemi** [comment]
Is there a better way in Ruby to implement this nested loop: 

```
pieces.each do |piece|   
  cellsTouched.each do |position|   
    return true if piece.position.x == position.x and piece.position.y == position.y
  end
end
```

The comparison can be done with piece.position.equal? instead. But for the loops I have not found a better way or a more Ruby-like way to implement this. 

All suggestions are welcome :)

**Comment by fleawig** [comment]
Well, the second loop can be on one line, and you can use the ruby variable name and operator conventions. 
(I'm writing this on my phone so it might not be perfect.)

You could also break out a private method for position_eq?(x), something like this (if it works w the block variables)

def position_eq?(x)
  true if piece.position.x == position.x
end 
So then you would have:

pieces.each do |piece|
  cells_touched.each { |position| true if position_eq?(x) && position_eq?(y) }
end

I can't test it on my phone, though.

**Comment by nrabbi** [comment]
I would recommend us pausing/suspending/commenting out the tests for now. We didn't have passing build in codeship in a long time, and it's a bad practice to work on broken builds for this long.

**Comment by fleawig** [comment]
I agree that option 2 makes sense (keep this separate branch just for fixing the tests).
I will be able to review this tomorrow morning.

**Comment by rongg** [comment]
@nrabbi I think option 2 means not only fixing the test files(which is already done) but also adding the implementations of is_obstructed. Right now we have failing tests on master which was my fault for merging the original is-obstructed branch as well as codeship breaking, but we can correct that from here on out by only merging successfully tested code.

**Comment by nrabbi** [comment]
@rongg I see, if there is a broken implementation, then we should just comment out the particular test code. That way we can still push all the files and pass codeship testing. We can remove the comment tag once everything is working. As long we can tackle the Codehip issue I am fine with any suggestions.

**Comment by rongg** [comment]
If an implementation is broken, we should fix it until the test passes. Our case is a little different here in that not only is some of the code not implemented, but the test code itself broke due to changes in the ChessPiece class structure.

If I'm understanding this correctly then Codeship is meant to remind us that our production code is ready. In our case the master branch is production, so at any given point the master branch should be able to be pushed to Heroku.

**Comment by rongg** [comment]
Looks like were only missing pawns and the queen

**Comment by nrabbi** [comment]
working version of pawns is_obstructed? method and tests are done.

**Comment by fleawig** [comment]
I did a spot review of all the pieces I found (this is everything except the Queen, right?) in addition to running the tests and they seemed good. Obviously we need to get the queen in there. Everything else looked ok. Really nice job, @ezschemi @nrabbi @rongg !

One comment for everyone -- run rubocop in terminal with command "rubocop". A bunch of unruby-ish code could be rewritten, esp when it comes to returns, self, operators, etc. Not that we need to enforce every single thing it caught, but maybe these bigger issues.

**Comment by nrabbi** [comment]
Guys, I put the queen tests to pending. The RSpec tests pass, but it fails on the rubocop tests. So basically, the codeship build will still fail until we fix the rubocop offenses.

**Comment by nrabbi** [comment]
Most of the rubocop offenses required project structural changes, so I only changed stuff that was possible without hampering the whole project structure. And yes this build is passing. Please review and merge to master once everything is okay with the changes. 

Note: I will manually merge the pull request to master if by 11:59 pm EST today if there are no objections.

**Pull request merged**
